; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-12832]
platform = https://github.com/platformio/platform-espressif32.git
board = esp32-s3-devkitc-1
framework = espidf

upload_speed = 921600
monitor_speed = 115200

board_upload.flash_size = 16MB

; 1. 开启 PSRAM 支持
build_flags = 
    -D BOARD_HAS_PSRAM
    ; 如果你的板子是 OPI 类型的 PSRAM（S3 常见 8MB/16MB 版本多为 OPI）
    -D CONFIG_SPIRAM_MODE_OCT=1

; 2. 指定内存类型
board_build.arduino.memory_type = qio_opi